import { HelpContentBundle, HelpSection, UserRole } from '@/types/help';

const ALL_ROLES: UserRole[] = ['super_admin', 'admin', 'bursar', 'teacher'];
const ADMIN_ROLES: UserRole[] = ['super_admin', 'admin'];
const BURSAR_ROLES: UserRole[] = ['super_admin', 'admin', 'bursar'];
const TEACHER_ROLES: UserRole[] = ['super_admin', 'admin', 'teacher'];

export const helpContent: HelpContentBundle = {
  sections: [
    {
      id: 'dashboard-overview',
      heading: 'Dashboard Overview and Navigation',
      description: 'Your central hub for monitoring school operations, key metrics, and quick actions.',
      roleVisibility: ALL_ROLES,
      order: 1,
      icon: 'LayoutDashboard',
      topics: [
        {
          id: 'understanding-dashboard',
          title: 'Understanding the Dashboard',
          roleVisibility: ALL_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Log in to your {{organizationName}} SchoolLedger account.' },
            { order: 2, instruction: 'The Dashboard displays KPI cards showing student counts, financial summaries, attendance rates, and transport usage at a glance.' },
            { order: 3, instruction: 'Use the Quick Actions section to jump directly to common tasks like recording payments or taking attendance.' },
            { order: 4, instruction: 'The Activity Feed shows recent events such as new enrollments, payments, and status changes.' },
          ],
          screenshotCaption: 'Dashboard overview showing KPI cards and activity feed',
          relatedModuleRoute: '/dashboard',
          tags: ['dashboard', 'overview', 'navigation', 'kpi'],
        },
        {
          id: 'sidebar-navigation',
          title: 'Using the Sidebar Navigation',
          roleVisibility: ALL_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'The left sidebar contains all modules available to your role. Items you do not have access to are hidden automatically.' },
            { order: 2, instruction: 'Click any sidebar item to navigate to that module. The active page is highlighted.' },
            { order: 3, instruction: 'On mobile devices, the sidebar collapses into a hamburger menu. Tap the menu icon to expand it.' },
          ],
          screenshotCaption: 'Sidebar navigation with active state',
          tags: ['sidebar', 'navigation', 'menu'],
        },
      ],
    },
    {
      id: 'school-setup',
      heading: 'School Setup and Configuration',
      description: 'Initial setup steps for new SchoolLedger tenants.',
      roleVisibility: ADMIN_ROLES,
      order: 2,
      icon: 'School',
      topics: [
        {
          id: 'completing-onboarding',
          title: 'Completing the Onboarding Wizard',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'After creating your account, the Onboarding Wizard guides you through essential setup.' },
            { order: 2, instruction: 'Step 1: Configure your academic calendar (terms and holidays).' },
            { order: 3, instruction: 'Step 2: Add your school classes and grade levels.' },
            { order: 4, instruction: 'Step 3: Set up tuition structures for each class or grade.' },
            { order: 5, instruction: 'Step 4: Complete your admin profile including contact details.' },
          ],
          screenshotCaption: 'Onboarding wizard step indicator',
          tags: ['onboarding', 'setup', 'wizard'],
        },
        {
          id: 'tenant-settings',
          title: 'Configuring Tenant Settings',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Navigate to Settings from the sidebar.' },
            { order: 2, instruction: 'Update your school name, logo, and contact information.' },
            { order: 3, instruction: 'Configure notification preferences and default currency.' },
          ],
          screenshotCaption: 'Tenant settings form',
          relatedModuleRoute: '/settings',
          tags: ['settings', 'tenant', 'configuration'],
        },
      ],
    },
    {
      id: 'academic-year',
      heading: 'Academic Year and Term Management',
      description: 'Manage academic calendars, terms, and holidays.',
      roleVisibility: ADMIN_ROLES,
      order: 3,
      icon: 'Calendar',
      topics: [
        {
          id: 'creating-academic-year',
          title: 'Creating an Academic Year',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Go to Settings > Academic Calendar.' },
            { order: 2, instruction: 'Click "Add Academic Year" and enter the year label (e.g., "2026").' },
            { order: 3, instruction: 'Define the start and end dates for the academic year.' },
            { order: 4, instruction: 'Save the academic year. It will become available for term creation.' },
          ],
          screenshotCaption: 'Academic year creation form',
          tags: ['academic year', 'calendar', 'terms'],
        },
        {
          id: 'adding-terms',
          title: 'Adding Terms and Holidays',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Within the Academic Calendar, select the academic year.' },
            { order: 2, instruction: 'Click "Add Term" and specify the term name (e.g., "Term 1"), start date, and end date.' },
            { order: 3, instruction: 'Add official holidays by clicking "Add Holiday" and selecting the date and description.' },
            { order: 4, instruction: 'Holidays are excluded from staff working-day calculations automatically.', tip: 'Ensure holidays are added before generating billing runs to avoid incorrect charge calculations.' },
          ],
          screenshotCaption: 'Term and holiday management interface',
          tags: ['terms', 'holidays', 'calendar'],
        },
      ],
    },
    {
      id: 'class-management',
      heading: 'Class and Student Management',
      description: 'Manage classes, enrollments, student records, and assignments.',
      roleVisibility: ADMIN_ROLES,
      order: 4,
      icon: 'Users',
      topics: [
        {
          id: 'creating-a-class',
          title: 'Creating a New Class',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Classes from the sidebar.' },
            { order: 2, instruction: 'Click the "New Class" button.' },
            { order: 3, instruction: 'Enter the class name, grade level, and select the academic year.' },
            { order: 4, instruction: 'Click Save to create the class.' },
          ],
          screenshotCaption: 'Class creation form with grade selector',
          relatedModuleRoute: '/classes',
          tags: ['class', 'create', 'enrollment'],
        },
        {
          id: 'enrolling-students',
          title: 'Enrolling Students in a Class',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Open the class detail page and click the "Students" tab.' },
            { order: 2, instruction: 'Click "Add Students" to open the enrollment modal.' },
            { order: 3, instruction: 'Search for students by name or admission number and select them.' },
            { order: 4, instruction: 'Confirm the enrollment. Students will be linked to the class for the current academic year.' },
          ],
          screenshotCaption: 'Student enrollment modal with search',
          tags: ['enrollment', 'students', 'class'],
        },
        {
          id: 'student-profile',
          title: 'Viewing and Editing Student Profiles',
          roleVisibility: ADMIN_ROLES,
          order: 3,
          steps: [
            { order: 1, instruction: 'Navigate to Students and click on a student\'s name.' },
            { order: 2, instruction: 'The profile page shows personal details, enrollment history, finance summary, and attendance records.' },
            { order: 3, instruction: 'Click "Edit" to update contact information or assign the student to a different class.' },
            { order: 4, instruction: 'Use the Finance tab to view the student\'s fee statement, payment history, and outstanding balance.' },
          ],
          screenshotCaption: 'Student profile with tabs',
          relatedModuleRoute: '/students',
          tags: ['student', 'profile', 'edit'],
        },
        {
          id: 'bulk-student-import',
          title: 'Bulk Importing Students',
          roleVisibility: ADMIN_ROLES,
          order: 4,
          steps: [
            { order: 1, instruction: 'Go to Students and click "Bulk Import".' },
            { order: 2, instruction: 'Download the CSV template to ensure your data is formatted correctly.' },
            { order: 3, instruction: 'Upload your CSV file. The system validates required fields and checks for duplicates.' },
            { order: 4, instruction: 'Review any validation errors, fix them in your CSV, and re-upload if needed.' },
            { order: 5, instruction: 'Click "Execute Import" to create the student records. Imported students remain unassigned until you enroll them in classes.' },
          ],
          screenshotCaption: 'Bulk import with CSV upload and validation',
          tags: ['import', 'bulk', 'csv', 'students'],
        },
      ],
    },
    {
      id: 'fee-structure',
      heading: 'Tuition Structure Creation and Management',
      description: 'Define tuition rules, assign them to classes, and manage billing categories.',
      roleVisibility: ADMIN_ROLES,
      order: 5,
      icon: 'ClipboardList',
      topics: [
        {
          id: 'creating-fee-rules',
          title: 'Creating Tuition Rules',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Settings > Tuition Structure.' },
            { order: 2, instruction: 'Click "Add Tuition Rule" to create a new billing rule.' },
            { order: 3, instruction: 'Enter the tuition name, amount, and billing cycle (monthly, termly, or annually).' },
            { order: 4, instruction: 'Set the assignment scope: "School-wide" applies to all students; "Class" applies to specific classes only.' },
            { order: 5, instruction: 'Save the tuition rule. It will become active for the next billing generation cycle.' },
          ],
          screenshotCaption: 'Tuition rule creation form',
          relatedModuleRoute: '/settings',
          tags: ['fee', 'rules', 'billing'],
        },
        {
          id: 'fee-categories',
          title: 'Managing Payment Categories',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Go to Settings > Payment Categories.' },
            { order: 2, instruction: 'System categories (Fees, Transport Fee) are protected and cannot be deleted.' },
            { order: 3, instruction: 'Add custom categories for specific school needs (e.g., "Extracurricular", "Uniform").' },
            { order: 4, instruction: 'Each category can have a default amount and description.' },
          ],
          screenshotCaption: 'Payment categories list',
          tags: ['categories', 'payment', 'fees'],
        },
      ],
    },
    {
      id: 'transport-configuration',
      heading: 'Transport Charge Configuration and Rules',
      description: 'Configure transport routes, stops, and monthly transport charges.',
      roleVisibility: ADMIN_ROLES,
      order: 6,
      icon: 'Bus',
      topics: [
        {
          id: 'creating-transport-routes',
          title: 'Creating Transport Routes',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Transport from the sidebar.' },
            { order: 2, instruction: 'Click "Add Route" and enter the route name, description, and monthly fee.' },
            { order: 3, instruction: 'Add stops along the route by specifying stop names and order positions.' },
            { order: 4, instruction: 'Assign a bus and driver to the route.' },
          ],
          screenshotCaption: 'Transport route creation with stops',
          relatedModuleRoute: '/transport',
          tags: ['transport', 'routes', 'bus'],
        },
        {
          id: 'assigning-students-transport',
          title: 'Assigning Students to Transport',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Open a transport route and click "Assign Students".' },
            { order: 2, instruction: 'Search for students and select them. Each student can only be on one active route at a time.' },
            { order: 3, instruction: 'Select the pickup and drop-off stops for each student.' },
            { order: 4, instruction: 'Save the assignments. Transport charges will be generated automatically in the billing cycle.' },
          ],
          screenshotCaption: 'Student transport assignment modal',
          tags: ['transport', 'students', 'assignment'],
        },
      ],
    },
    {
      id: 'billing-workflow',
      heading: 'Billing Workflow and Invoice Generation',
      description: 'Generate charges, create billing runs, and manage student invoices.',
      roleVisibility: BURSAR_ROLES,
      order: 7,
      icon: 'FileText',
      topics: [
        {
          id: 'generating-fee-charges',
          title: 'Generating Tuition Charges',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Billing from the sidebar.' },
            { order: 2, instruction: 'Select the billing period (term or month) and the tuition rules to apply.' },
            { order: 3, instruction: 'The system calculates charges for all eligible students based on their class assignments and tuition rules.' },
            { order: 4, instruction: 'Review the preview of charges before confirming generation.' },
            { order: 5, instruction: 'Click "Generate Charges" to create the billing batch. Charges can be rolled back if needed.' },
          ],
          screenshotCaption: 'Billing generation preview panel',
          relatedModuleRoute: '/billing',
          tags: ['billing', 'charges', 'invoice', 'generation'],
        },
        {
          id: 'generating-transport-charges',
          title: 'Generating Transport Charges',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'In the Billing tab, switch to the Transport Charges section.' },
            { order: 2, instruction: 'Select the month (format: YYYY-MM) for which to generate transport charges.' },
            { order: 3, instruction: 'The system calculates charges for all students assigned to active transport routes.' },
            { order: 4, instruction: 'Review and confirm the transport charge batch.' },
          ],
          screenshotCaption: 'Transport charge generation with month picker',
          tags: ['transport', 'billing', 'charges'],
        },
        {
          id: 'rolling-back-charges',
          title: 'Rolling Back Charge Batches',
          roleVisibility: ADMIN_ROLES,
          order: 3,
          steps: [
            { order: 1, instruction: 'In Billing, view the list of generated charge batches.' },
            { order: 2, instruction: 'Find the batch you need to reverse and click "Void Batch".' },
            { order: 3, instruction: 'Enter a reason for the rollback (required for audit purposes).' },
            { order: 4, instruction: 'Confirm the void. All charges in the batch will be marked as voided and excluded from balance calculations.' },
          ],
          screenshotCaption: 'Charge batch void confirmation dialog',
          tags: ['rollback', 'void', 'charges', 'billing'],
        },
        {
          id: 'viewing-invoices',
          title: 'Viewing and Managing Invoices',
          roleVisibility: BURSAR_ROLES,
          order: 4,
          steps: [
            { order: 1, instruction: 'Navigate to the student profile and open the Finance tab.' },
            { order: 2, instruction: 'The Billed/Charges section shows all generated charges with their status: Not Paid, Partially Paid, or Paid.' },
            { order: 3, instruction: 'Use the month/year filters to narrow down charges for a specific period.' },
            { order: 4, instruction: 'Export the fee statement as a PDF for parent meetings or record-keeping.' },
          ],
          screenshotCaption: 'Student fee statement with status badges',
          tags: ['invoice', 'view', 'statement', 'bursar'],
        },
      ],
    },
    {
      id: 'recording-payments',
      heading: 'Payment Recording and Reconciliation',
      description: 'Record student payments, manage receipts, and reconcile accounts.',
      roleVisibility: BURSAR_ROLES,
      order: 8,
      icon: 'Banknote',
      topics: [
        {
          id: 'recording-a-payment',
          title: 'Recording a Student Payment',
          roleVisibility: BURSAR_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Payments from the sidebar.' },
            { order: 2, instruction: 'Click "Record Payment" to open the payment modal.' },
            { order: 3, instruction: 'Select the student by name or admission number.' },
            { order: 4, instruction: 'Enter the payment amount, method (Cash, Bank Transfer, Mobile Money, Card), and date.' },
            { order: 5, instruction: 'Choose the payment category (Fees, Transport Fee, or custom categories).' },
            { order: 6, instruction: 'Optionally enable "Split across categories" to divide the payment among multiple categories.' },
            { order: 7, instruction: 'Click "Record Payment" to save. The system automatically allocates the payment to outstanding charges using FIFO logic.' },
          ],
          screenshotCaption: 'Record payment modal with category split',
          relatedModuleRoute: '/payments',
          tags: ['payment', 'record', 'student'],
        },
        {
          id: 'managing-receipts',
          title: 'Managing Receipts',
          roleVisibility: BURSAR_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'After recording a payment, the receipt is generated automatically with a unique receipt number.' },
            { order: 2, instruction: 'Click "View Receipt" on any payment row to see the full receipt details.' },
            { order: 3, instruction: 'Print or download the receipt as a PDF for parent records.' },
            { order: 4, instruction: 'Receipts include student name, class, payment amount, method, date, and remaining balance.' },
          ],
          screenshotCaption: 'Receipt document view with print option',
          tags: ['receipt', 'print', 'payment'],
        },
        {
          id: 'reconciliation',
          title: 'Daily Reconciliation Procedures',
          roleVisibility: BURSAR_ROLES,
          order: 3,
          steps: [
            { order: 1, instruction: 'At the end of each day, navigate to Settings > Reconciliation.' },
            { order: 2, instruction: 'Review the daily payment summary showing total collected by method (cash, transfer, etc.).' },
            { order: 3, instruction: 'Compare the system totals with your physical cash box or bank statements.' },
            { order: 4, instruction: 'Record any discrepancies as ledger adjustments with a reason.' },
            { order: 5, instruction: 'Submit the reconciliation to lock the day\'s records and generate an audit trail.' },
          ],
          screenshotCaption: 'Reconciliation dashboard with daily totals',
          tags: ['reconciliation', 'daily', 'audit', 'bursar'],
        },
      ],
    },
    {
      id: 'user-role-management',
      heading: 'User and Role Management',
      description: 'Manage staff accounts, roles, and permissions.',
      roleVisibility: ADMIN_ROLES,
      order: 9,
      icon: 'UserCog',
      topics: [
        {
          id: 'inviting-users',
          title: 'Inviting New Users',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Settings > User Accounts.' },
            { order: 2, instruction: 'Click "Invite User" and enter the email address and name.' },
            { order: 3, instruction: 'Select the role: Admin (full access), Bursar (financial access), or Teacher (attendance only).' },
            { order: 4, instruction: 'The invited user receives an email with a temporary password and login link.' },
          ],
          screenshotCaption: 'User invitation form with role selector',
          relatedModuleRoute: '/settings',
          tags: ['users', 'invite', 'roles', 'permissions'],
        },
        {
          id: 'managing-roles',
          title: 'Managing Roles and Permissions',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'In User Accounts, view the list of all users in your tenant.' },
            { order: 2, instruction: 'Click on a user to edit their role or deactivate their account.' },
            { order: 3, instruction: 'Role changes take effect immediately. Deactivated users can no longer log in.' },
          ],
          screenshotCaption: 'User accounts table with role badges',
          tags: ['roles', 'permissions', 'users'],
        },
      ],
    },
    {
      id: 'reports-analytics',
      heading: 'Reports and Analytics',
      description: 'Generate financial, attendance, and enrollment reports.',
      roleVisibility: BURSAR_ROLES,
      order: 10,
      icon: 'BarChart3',
      topics: [
        {
          id: 'financial-reports',
          title: 'Financial Reports',
          roleVisibility: BURSAR_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to the Reports or Dashboard section.' },
            { order: 2, instruction: 'View the Financial Summary showing total outstanding, payments collected, and collection rate.' },
            { order: 3, instruction: 'Filter reports by date range, class, or payment method.' },
            { order: 4, instruction: 'Export reports as CSV for spreadsheet analysis or PDF for presentations.' },
          ],
          screenshotCaption: 'Financial report with filters and export',
          tags: ['reports', 'financial', 'export', 'analytics'],
        },
        {
          id: 'attendance-reports',
          title: 'Attendance Reports',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Navigate to Staff Attendance > Reports tab.' },
            { order: 2, instruction: 'Generate period reports by selecting a date range and optionally filtering by department or staff member.' },
            { order: 3, instruction: 'View department-level rollups showing attendance rates, late arrivals, and on-leave counts.' },
            { order: 4, instruction: 'Export the report as CSV or PDF.' },
          ],
          screenshotCaption: 'Attendance period report with department rollup',
          tags: ['attendance', 'reports', 'staff'],
        },
      ],
    },
    {
      id: 'system-settings',
      heading: 'System Settings and Configuration',
      description: 'Configure platform-wide settings, integrations, and preferences.',
      roleVisibility: ADMIN_ROLES,
      order: 11,
      icon: 'Settings',
      topics: [
        {
          id: 'general-settings',
          title: 'General Settings',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Settings > General.' },
            { order: 2, instruction: 'Update your school name, address, and contact details.' },
            { order: 3, instruction: 'Configure the default currency and timezone.' },
            { order: 4, instruction: 'Set the student attendance mode (per day or per class session).' },
          ],
          screenshotCaption: 'General settings form',
          relatedModuleRoute: '/settings',
          tags: ['settings', 'general', 'configuration'],
        },
        {
          id: 'charge-proration',
          title: 'Charge Proration Settings',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Go to Settings > Tuition Structure > Charge Proration.' },
            { order: 2, instruction: 'Toggle "Enable Charge Proration" to automatically prorate tuition for students who join mid-term.' },
            { order: 3, instruction: 'When enabled, the system calculates a prorated amount based on the remaining days in the billing period.' },
          ],
          screenshotCaption: 'Charge proration toggle card',
          tags: ['proration', 'settings', 'fees'],
        },
      ],
    },
    {
      id: 'best-practices',
      heading: 'Best Practices and Recommended Workflows',
      description: 'Operational recommendations for efficient school management.',
      roleVisibility: ADMIN_ROLES,
      order: 12,
      icon: 'Lightbulb',
      topics: [
        {
          id: 'recommended-workflow',
          title: 'Recommended Monthly Workflow',
          roleVisibility: ADMIN_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Start of Month: Review and update the academic calendar if needed.' },
            { order: 2, instruction: 'Week 1: Generate tuition charges for the new month or term.' },
            { order: 3, instruction: 'Week 2: Generate transport charges for the current month.' },
            { order: 4, instruction: 'Daily: Record payments as they arrive. Run reconciliation at end of day.' },
            { order: 5, instruction: 'End of Month: Review financial reports, follow up on outstanding balances, and export records for archiving.' },
          ],
          tags: ['workflow', 'best practices', 'monthly'],
        },
        {
          id: 'data-backup',
          title: 'Data Backup and Security',
          roleVisibility: ADMIN_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Ensure all user accounts have strong, unique passwords.' },
            { order: 2, instruction: 'Regularly review user access and deactivate accounts for departing staff.' },
            { order: 3, instruction: 'Export critical reports (enrollment, financial) monthly for offline backup.' },
            { order: 4, instruction: 'Monitor the audit log in Settings > Reconciliation for any unusual activity.' },
          ],
          tags: ['backup', 'security', 'audit', 'best practices'],
        },
      ],
    },
    {
      id: 'troubleshooting',
      heading: 'Common Troubleshooting and FAQs',
      description: 'Solutions to common issues faced by administrators.',
      roleVisibility: ADMIN_ROLES,
      order: 13,
      icon: 'Wrench',
      topics: [
        {
          id: 'login-issues',
          title: 'I Cannot Log In',
          roleVisibility: ALL_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Verify you are using the correct email address and password.' },
            { order: 2, instruction: 'If you forgot your password, click "Forgot Password" on the login page to reset it.' },
            { order: 3, instruction: 'If your account was deactivated, contact your school administrator.' },
            { order: 4, instruction: 'Check that your internet connection is stable.' },
          ],
          tags: ['login', 'troubleshooting', 'password'],
        },
        {
          id: 'balance-discrepancy',
          title: 'Student Balance Does Not Look Correct',
          roleVisibility: BURSAR_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Open the student profile and go to the Finance tab.' },
            { order: 2, instruction: 'Review the fee statement to see all charges, payments, and adjustments.' },
            { order: 3, instruction: 'Check if any charge batches were voided, which would remove charges from the balance.' },
            { order: 4, instruction: 'Verify that payments were recorded under the correct category (Fees vs Transport Fee).' },
            { order: 5, instruction: 'If the discrepancy persists, create a ledger adjustment with a detailed reason.' },
          ],
          tags: ['balance', 'discrepancy', 'troubleshooting', 'bursar'],
        },
        {
          id: 'missing-students',
          title: 'Students Are Missing from a Class',
          roleVisibility: ADMIN_ROLES,
          order: 3,
          steps: [
            { order: 1, instruction: 'Navigate to Students and check the student\'s status. Inactive or withdrawn students will not appear in class lists.' },
            { order: 2, instruction: 'Verify the student is enrolled in the correct academic year and term.' },
            { order: 3, instruction: 'Check if the class assignment was removed accidentally. Re-enroll the student if needed.' },
            { order: 4, instruction: 'If the student was bulk-imported, ensure they were enrolled into a class after import.' },
          ],
          tags: ['students', 'missing', 'class', 'troubleshooting'],
        },
      ],
    },
    {
      id: 'bursar-financial',
      heading: 'Bursar Financial Operations',
      description: 'Financial workflows specific to bursar responsibilities.',
      roleVisibility: BURSAR_ROLES,
      order: 14,
      icon: 'Wallet',
      topics: [
        {
          id: 'viewing-balances',
          title: 'Viewing Students and Account Balances',
          roleVisibility: BURSAR_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Students from the sidebar.' },
            { order: 2, instruction: 'The student list shows each student\'s name, class, and outstanding balance.' },
            { order: 3, instruction: 'Click on any student to view their detailed finance summary.' },
            { order: 4, instruction: 'Use the balance filter to find students with overdue amounts.' },
          ],
          screenshotCaption: 'Students list with balance column',
          relatedModuleRoute: '/students',
          tags: ['balances', 'students', 'bursar', 'view'],
        },
        {
          id: 'monitoring-outstanding',
          title: 'Monitoring Outstanding Balances',
          roleVisibility: BURSAR_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'From the Dashboard, view the "Total Outstanding" KPI card.' },
            { order: 2, instruction: 'Navigate to the Payments page and use filters to show students with outstanding balances.' },
            { order: 3, instruction: 'Generate a fee statement report for follow-up with parents or guardians.' },
            { order: 4, instruction: 'Use the "Overdue" filter to identify accounts that need immediate attention.' },
          ],
          tags: ['outstanding', 'balances', 'monitoring', 'bursar'],
        },
      ],
    },
    {
      id: 'teacher-attendance',
      heading: 'Marking Student Attendance',
      description: 'How teachers record daily student attendance.',
      roleVisibility: TEACHER_ROLES,
      order: 15,
      icon: 'ClipboardCheck',
      topics: [
        {
          id: 'daily-attendance',
          title: 'Taking Daily Attendance',
          roleVisibility: TEACHER_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Navigate to Attendance from the sidebar.' },
            { order: 2, instruction: 'Select the date and class you are marking attendance for.' },
            { order: 3, instruction: 'Mark each student as Present, Absent, Late, or Excused using the status buttons.' },
            { order: 4, instruction: 'Add optional notes for absences or late arrivals.' },
            { order: 5, instruction: 'Click "Save Attendance" to submit the daily record.' },
          ],
          screenshotCaption: 'Attendance marking grid with status buttons',
          relatedModuleRoute: '/attendance',
          tags: ['attendance', 'daily', 'teacher', 'marking'],
        },
        {
          id: 'viewing-rosters',
          title: 'Viewing Class Rosters',
          roleVisibility: TEACHER_ROLES,
          order: 2,
          steps: [
            { order: 1, instruction: 'Navigate to Classes from the sidebar.' },
            { order: 2, instruction: 'Click on your assigned class to open the class detail page.' },
            { order: 3, instruction: 'The Students tab shows the full roster with names, admission numbers, and contact details.' },
            { order: 4, instruction: 'Use the search bar to find a specific student quickly.' },
          ],
          screenshotCaption: 'Class roster table with student details',
          relatedModuleRoute: '/classes',
          tags: ['roster', 'class', 'students', 'teacher'],
        },
      ],
    },
    {
      id: 'teacher-troubleshooting',
      heading: 'Teacher Troubleshooting',
      description: 'Common issues and solutions for teachers.',
      roleVisibility: TEACHER_ROLES,
      order: 16,
      icon: 'HelpCircle',
      topics: [
        {
          id: 'attendance-not-saving',
          title: 'Attendance Changes Are Not Saving',
          roleVisibility: TEACHER_ROLES,
          order: 1,
          steps: [
            { order: 1, instruction: 'Ensure you have clicked "Save Attendance" after making changes.' },
            { order: 2, instruction: 'Check your internet connection. If offline, changes may not sync.' },
            { order: 3, instruction: 'Refresh the page and verify the attendance reflects your entries.' },
            { order: 4, instruction: 'If the issue persists, contact your school administrator.' },
          ],
          tags: ['attendance', 'saving', 'troubleshooting', 'teacher'],
        },
      ],
    },
  ],
  contextualMappings: [
    {
      moduleRoute: '/dashboard',
      targetSectionId: 'dashboard-overview',
      label: 'Dashboard Help',
      roleVisibility: ALL_ROLES,
    },
    {
      moduleRoute: '/classes',
      targetSectionId: 'class-management',
      label: 'Class Management Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/students',
      targetSectionId: 'class-management',
      label: 'Student Management Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/payments',
      targetSectionId: 'recording-payments',
      label: 'Payment Recording Help',
      roleVisibility: BURSAR_ROLES,
    },
    {
      moduleRoute: '/billing',
      targetSectionId: 'billing-workflow',
      label: 'Billing Workflow Help',
      roleVisibility: BURSAR_ROLES,
    },
    {
      moduleRoute: '/settings',
      targetSectionId: 'system-settings',
      label: 'System Settings Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/staff',
      targetSectionId: 'user-role-management',
      label: 'User Management Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/staff-attendance',
      targetSectionId: 'reports-analytics',
      label: 'Attendance Reports Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/transport',
      targetSectionId: 'transport-configuration',
      label: 'Transport Configuration Help',
      roleVisibility: ADMIN_ROLES,
    },
    {
      moduleRoute: '/attendance',
      targetSectionId: 'teacher-attendance',
      label: 'Attendance Help',
      roleVisibility: TEACHER_ROLES,
    },
  ],
};

/**
 * Filter sections and topics by the given user role.
 * Returns only sections/topics the role is authorized to see.
 */
export function getSectionsForRole(
  sections: HelpSection[],
  role: UserRole
): HelpSection[] {
  return sections
    .filter((section) => section.roleVisibility.includes(role))
    .map((section) => ({
      ...section,
      topics: section.topics.filter((topic) =>
        topic.roleVisibility.includes(role)
      ),
    }))
    .filter((section) => section.topics.length > 0);
}

/**
 * Check if a section is visible to a given role.
 */
export function isSectionVisibleToRole(
  section: HelpSection,
  role: UserRole
): boolean {
  return section.roleVisibility.includes(role);
}
